<?php
$template = 'hdc_';
define("admin",$template."admin",true);
define("province",$template."province",true);
define("members",$template."members",true);
define("bodem",$template."bodem",true);
define("member2",$template."member2",true);
define("shoppingCart",$template."shoppingcart",true);
define("intro",$template."intro",true);
define("guide",$template."guide",true);
define("menu_product",$template."menu_product",true);
define("product",$template."product",true);
define("ads",$template."ads",true);
define("support",$template."support",true);
define("contact",$template."contact",true);
define("download",$template."download",true);
define("opinion",$template."opinion",true);
define("product2",$template."product2",true);
define("menu_product2",$template."menu_product2",true);
define("menu_anh",$template."menu_anh",true);
define("anh",$template."anh",true);
define("comment",$template."comment",true);
define("bottom",$template."bottom",true);
define("contact2",$template."contact2",true);
define("website",$template."website",true);
?>